export const FETCH_BOOKS_LOADING = 'FETCH_BOOKS_LOADING'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE'

export const FETCH_BOOK_LOADING = 'FETCH_BOOK_LOADING'
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS'
export const FETCH_BOOK_FAILURE = 'FETCH_BOOK_FAILURE'

export const POST_BOOK_LOADING = 'POST_BOOK_LOADING'
export const POST_BOOK_SUCCESS = 'POST_BOOK_SUCCESS'
export const POST_BOOK_FAILURE = 'POST_BOOK_FAILURE'

export const PATCH_BOOK_LOADING = 'PATCH_BOOK_LOADING'
export const PATCH_BOOK_SUCCESS = 'PATCH_BOOK_SUCCESS'
export const PATCH_BOOK_FAILURE = 'PATCH_BOOK_FAILURE'

export const DELETE_BOOK_LOADING = 'DELETE_BOOK_LOADING'
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS'
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE'

export const FETCH_COVERS_LOADING = 'FETCH_COVERS_LOADING'
export const FETCH_COVERS_SUCCESS = 'FETCH_COVERS_SUCCESS'
export const FETCH_COVERS_FAILURE = 'FETCH_COVERS_FAILURE'

export const FETCH_COVER_LOADING = 'FETCH_COVER_LOADING'
export const FETCH_COVER_SUCCESS = 'FETCH_COVER_SUCCESS'
export const FETCH_COVER_FAILURE = 'FETCH_COVER_FAILURE'