version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /root/ssl:/ssl
    depends_on:
      - api
  client:
    container_name: client
    restart: always
    stdin_open: true
    build:
        context: ./client
        dockerfile: ./Dockerfile
    volumes: 
        - ./client:/usr/src/client
        - /usr/src/client/node_modules
    depends_on: 
        - api      
  db:
    image: 'mongo'
    restart: always
    container_name: 'books-mongo-container'
    environment: 
      - MOGO_INITDB_DATABASE=LIBRARY
      - MONGO_INITDB_ROOT_USERNAME=librarian
      - MONGO_INITDB_ROOT_PASSWORD=libpassword 
      - MONGODB_USER="librarian" 
      - MONGODB_PASS="libpassword"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api
    restart: always
    build:
        context: ./hell_back
        dockerfile: ./Dockerfile
    ports:
        - 8000:8000
    volumes:
        - ./server_self:/usr/src/api
        - /usr/src/api/node_modules
    depends_on:
        - db